/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the API is up and can reach its database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Listings
         * @description The marketing site's listings: `getProperties()` in the frontend.
         *     Each filter is optional and they combine.
         */
        get: operations["list_listings_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Listing
         * @description One listing: `getPropertyBySlug()` in the frontend.
         */
        get: operations["get_listing_listings__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Worklist
         * @description Everything assigned to this technician. Open work is ordered started
         *     first, then emergencies, then oldest; closed work, most recently closed
         *     first.
         */
        get: operations["get_worklist_technicians__technician_id__worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description One job. Refused (403) if this technician doesn't hold it.
         */
        get: operations["get_job_technicians__technician_id__jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Job
         * @description Arriving on site: moves the job to in-progress. Starting a job already
         *     under way changes nothing.
         */
        post: operations["start_job_technicians__technician_id__jobs__job_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Job
         * @description Closes a started job. Needs at least two photos of the work.
         */
        post: operations["complete_job_technicians__technician_id__jobs__job_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/hand-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand Back Job
         * @description 'Can't do it': the job goes back to the office unassigned, with the
         *     reason. It's no longer this technician's, so the request comes back
         *     rather than a job.
         */
        post: operations["hand_back_job_technicians__technician_id__jobs__job_id__hand_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CompleteJobIn */
        CompleteJobIn: {
            /** Notes */
            notes?: string | null;
            /**
             * Photos
             * @default []
             */
            photos: components["schemas"]["PhotoIn"][];
        };
        /**
         * ErrorOut
         * @description Every refusal: a message the frontend can show as it is.
         */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandBackIn */
        HandBackIn: {
            /** Reason */
            reason?: string | null;
        };
        /** HandBackOut */
        HandBackOut: {
            /** Reason */
            reason: string;
            /** By */
            by: string | null;
            /** Byname */
            byName: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /**
             * Database
             * @enum {string}
             */
            database: "connected" | "unreachable";
        };
        /**
         * JobOut
         * @description Built with `JobOut.from_model(request, repeat_fault=...)`.
         */
        JobOut: {
            /** Id */
            id: string;
            /** Unitid */
            unitId: string;
            /** Tenantid */
            tenantId: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "maintenance" | "housekeeping";
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Assigneeid */
            assigneeId: string | null;
            /** Origin */
            origin: ("ops" | "tenant") | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Stagehistory */
            stageHistory: components["schemas"]["StageEntryOut"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Charge */
            charge: number | null;
            /** Completionnotes */
            completionNotes: string | null;
            schedule: components["schemas"]["ScheduleOut"] | null;
            /** Completionphotos */
            completionPhotos: components["schemas"]["PhotoOut"][];
            handBack: components["schemas"]["HandBackOut"] | null;
            unit: components["schemas"]["UnitOut"];
            property: components["schemas"]["PropertyOut"];
            tenant: components["schemas"]["TenantOut"] | null;
            assignee: components["schemas"]["StaffOut"] | null;
            repeatFault: components["schemas"]["RepeatFaultOut"] | null;
        };
        /**
         * ListingOut
         * @description `Listing` in types.ts.
         */
        ListingOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Purpose */
            purpose: string;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            /** Bedrooms */
            bedrooms: number;
            /** Bathrooms */
            bathrooms: number;
            /** Areasqft */
            areaSqft: number;
            location: components["schemas"]["LocationOut"];
            /** Images */
            images: string[];
            /** Description */
            description: string;
            /** Featured */
            featured: boolean;
        };
        /** LocationOut */
        LocationOut: {
            /** City */
            city: string;
            /** Area */
            area: string;
        };
        /**
         * PhotoIn
         * @description `PhotoInput` in types.ts: anything without bytes is dropped.
         */
        PhotoIn: {
            /** Name */
            name?: string | null;
            /** Dataurl */
            dataUrl?: string | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Name */
            name: string;
            /** Dataurl */
            dataUrl: string;
        };
        /** PropertyOut */
        PropertyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /**
         * RepeatFaultOut
         * @description A unit that keeps failing the same way: the repair-versus-replace
         *     signal. Derived when read, never stored.
         */
        RepeatFaultOut: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Spend */
            spend: number;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Slot */
            slot: string;
        };
        /**
         * ServiceRequestOut
         * @description `ServiceRequest` in types.ts. `stage` and `createdAt` are read from the
         *     history (see the model); `schedule` and `handBack` are rebuilt from their
         *     columns.
         */
        ServiceRequestOut: {
            /** Id */
            id: string;
            /** Unitid */
            unitId: string;
            /** Tenantid */
            tenantId: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "maintenance" | "housekeeping";
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Assigneeid */
            assigneeId: string | null;
            /** Origin */
            origin: ("ops" | "tenant") | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Stagehistory */
            stageHistory: components["schemas"]["StageEntryOut"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Charge */
            charge: number | null;
            /** Completionnotes */
            completionNotes: string | null;
            schedule: components["schemas"]["ScheduleOut"] | null;
            /** Completionphotos */
            completionPhotos: components["schemas"]["PhotoOut"][];
            handBack: components["schemas"]["HandBackOut"] | null;
        };
        /** StaffOut */
        StaffOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "maintenance" | "housekeeping";
            /** Photo */
            photo: string | null;
        };
        /** StageEntryOut */
        StageEntryOut: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** TenantOut */
        TenantOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
        };
        /** UnitOut */
        UnitOut: {
            /** Id */
            id: string;
            /** Propertyid */
            propertyId: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "occupied" | "under-maintenance" | "vacant";
            /** Tenantid */
            tenantId: string | null;
            /** Bedrooms */
            bedrooms: number;
            /** Bathrooms */
            bathrooms: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorklistCounts */
        WorklistCounts: {
            /** Left */
            left: number;
            /** Urgent */
            urgent: number;
            /** Closed */
            closed: number;
        };
        /**
         * WorklistOut
         * @description One technician's own work, split the way the screen draws it: the job
         *     to lead with, the rest queued behind it, and what's closed.
         */
        WorklistOut: {
            technician: components["schemas"]["StaffOut"];
            next: components["schemas"]["JobOut"] | null;
            /** Queued */
            queued: components["schemas"]["JobOut"][];
            /** Closed */
            closed: components["schemas"]["JobOut"][];
            counts: components["schemas"]["WorklistCounts"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_listings_listings_get: {
        parameters: {
            query?: {
                purpose?: string | null;
                type?: string | null;
                featured?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listing_listings__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worklist_technicians__technician_id__worklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_technicians__technician_id__jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_technicians__technician_id__jobs__job_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_job_technicians__technician_id__jobs__job_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteJobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hand_back_job_technicians__technician_id__jobs__job_id__hand_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandBackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
