/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Whether the API is up and can reach its database.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Listings
         * @description The marketing site's listings: `getProperties()` in the frontend.
         *     Each filter is optional and they combine.
         */
        get: operations["list_listings_listings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/listings/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Listing
         * @description One listing: `getPropertyBySlug()` in the frontend.
         */
        get: operations["get_listing_listings__slug__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/worklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Worklist
         * @description Everything assigned to this technician. Open work is ordered started
         *     first, then emergencies, then oldest; closed work, most recently closed
         *     first.
         */
        get: operations["get_worklist_technicians__technician_id__worklist_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description One job. Refused (403) if this technician doesn't hold it.
         */
        get: operations["get_job_technicians__technician_id__jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Start Job
         * @description Arriving on site: moves the job to in-progress. Starting a job already
         *     under way changes nothing.
         */
        post: operations["start_job_technicians__technician_id__jobs__job_id__start_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Complete Job
         * @description Closes a started job. Needs at least two photos of the work.
         */
        post: operations["complete_job_technicians__technician_id__jobs__job_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/technicians/{technician_id}/jobs/{job_id}/hand-back": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Hand Back Job
         * @description 'Can't do it': the job goes back to the office unassigned, with the
         *     reason. It's no longer this technician's, so the request comes back
         *     rather than a job.
         */
        post: operations["hand_back_job_technicians__technician_id__jobs__job_id__hand_back_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Requests
         * @description The queue: `getRequests`. Filters narrow together; oldest first unless
         *     `sort=newest`.
         */
        get: operations["list_requests_requests_get"];
        put?: never;
        /**
         * Create Request
         * @description Raise a request, from ops, the housekeeping portal or a tenant:
         *     `createRequest`.
         */
        post: operations["create_request_requests_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Request
         * @description One request with what it points at: `getRequestById`.
         */
        get: operations["get_request_requests__request_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/{request_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assignment Candidates
         * @description Who could take this request, best first: `getAssignmentCandidates`.
         */
        get: operations["assignment_candidates_requests__request_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/assign": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Assign Requests
         * @description Give requests to one staff member: `assignRequests`. Closed work is
         *     skipped.
         */
        post: operations["assign_requests_requests_assign_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/priority": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Set Priority
         * @description `setPriority`.
         */
        post: operations["set_priority_requests_priority_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/requests/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Delete Requests
         * @description Remove requests entirely: `deleteRequests`. Returns them as they were.
         */
        post: operations["delete_requests_requests_delete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Units
         * @description Units with one trade's counts and spend, busiest first: `getUnits`.
         */
        get: operations["list_units_units_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/units/{unit_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Unit
         * @description One unit: `getUnitById`.
         */
        get: operations["get_unit_units__unit_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Properties
         * @description The buildings operations manages, by name: operations.ts's
         *     `getProperties`. (Marketing listings are `/listings`.)
         */
        get: operations["list_properties_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/properties": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Property Rollups
         * @description Cost and volume by building, most spend first: `getPropertyRollups`.
         */
        get: operations["property_rollups_reports_properties_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Category Rollups
         * @description Volume and spend by category, busiest first: `getCategoryRollups`,
         *     without labels.
         */
        get: operations["category_rollups_reports_categories_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/reports/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dashboard
         * @description The dashboard's numbers: `getDashboardStats`.
         */
        get: operations["dashboard_reports_dashboard_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Roster
         * @description One trade's current staff with the load they hold: `getStaffRoster`.
         */
        get: operations["roster_staff_roster_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Staff
         * @description One staff member, retired or not.
         */
        get: operations["get_staff_staff__staff_id__get"];
        /**
         * Update Staff
         * @description `updateStaff`. Leaving `photo` out keeps the one they have.
         */
        put: operations["update_staff_staff__staff_id__put"];
        post?: never;
        /**
         * Retire Staff
         * @description `removeStaff`: takes them off the roster once they hold no open work.
         *     Their closed work still names them.
         */
        delete: operations["retire_staff_staff__staff_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Staff
         * @description `addStaff`.
         */
        post: operations["add_staff_staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/housekeeping-rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Rates
         * @description The card, in its order: `getHousekeepingRates`. `includeRetired` adds
         *     the services that have left it, so old bookings can still be named.
         */
        get: operations["list_rates_housekeeping_rates_get"];
        put?: never;
        /**
         * Add Rate
         * @description `addHousekeepingRate`: goes at the end of the card.
         */
        post: operations["add_rate_housekeeping_rates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/housekeeping-rates/{service_type}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Retire Rate
         * @description `removeHousekeepingRate`: takes it off the card once no open booking
         *     uses it. Bookings already made keep its name and their price.
         */
        delete: operations["retire_rate_housekeeping_rates__service_type__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/{tenant_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Tenant
         * @description A tenant with the unit they occupy: `getTenantById`. The tenant
         *     portal's notifications and history are built from `/requests?tenantId=`.
         */
        get: operations["get_tenant_tenants__tenant_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssignIn */
        AssignIn: {
            /** Ids */
            ids: string[];
            /** Assigneeid */
            assigneeId: string;
        };
        /**
         * CandidateOut
         * @description A roster member ranked for one request's assign panel.
         */
        CandidateOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "maintenance" | "housekeeping";
            /** Photo */
            photo: string | null;
            /** Retiredat */
            retiredAt: string | null;
            /** Load */
            load: number;
            /** Capacity */
            capacity: number;
            /** Inprogress */
            inProgress: number;
            /** Closed */
            closed: number;
            /** Properties */
            properties: components["schemas"]["PropertyOut"][];
            /** Inbuilding */
            inBuilding: boolean;
            /** Atcapacity */
            atCapacity: boolean;
            /** Iscurrent */
            isCurrent: boolean;
            /** Score */
            score: number;
        };
        /**
         * CategoryRollupOut
         * @description `CategoryRollup` without `label`, which the frontend adds.
         */
        CategoryRollupOut: {
            /** Category */
            category: string;
            /** Requests */
            requests: number;
            /** Spend */
            spend: number;
        };
        /** CompleteJobIn */
        CompleteJobIn: {
            /** Notes */
            notes?: string | null;
            /**
             * Photos
             * @default []
             */
            photos: components["schemas"]["PhotoIn"][];
        };
        /** DashboardOut */
        DashboardOut: {
            /** Open */
            open: number;
            /** Unassigned */
            unassigned: number;
            /** Inprogress */
            inProgress: number;
            /** Closed */
            closed: number;
            /** Bystage */
            byStage: components["schemas"]["StageCount"][];
            /** Raised */
            raised: number;
            /** Urgentopen */
            urgentOpen: number;
            /** Urgentbuildings */
            urgentBuildings: number;
            /** Maintenancespend */
            maintenanceSpend: number;
            /** Periodspend */
            periodSpend: number;
            /** Costtrend */
            costTrend: components["schemas"]["MonthTotal"][];
        };
        /**
         * EnrichedRequestOut
         * @description `EnrichedRequest` in the frontend's operations.ts: a request with the
         *     records it points at. The frontend adds `tier` itself with `tierFor()`.
         */
        EnrichedRequestOut: {
            /** Id */
            id: string;
            /** Unitid */
            unitId: string;
            /** Tenantid */
            tenantId: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "maintenance" | "housekeeping";
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Assigneeid */
            assigneeId: string | null;
            /** Origin */
            origin: ("ops" | "tenant") | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Stagehistory */
            stageHistory: components["schemas"]["StageEntryOut"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Charge */
            charge: number | null;
            /** Completionnotes */
            completionNotes: string | null;
            schedule: components["schemas"]["ScheduleOut"] | null;
            /** Completionphotos */
            completionPhotos: components["schemas"]["PhotoOut"][];
            handBack: components["schemas"]["HandBackOut"] | null;
            unit: components["schemas"]["UnitOut"];
            property: components["schemas"]["PropertyOut"];
            tenant: components["schemas"]["TenantOut"] | null;
            assignee: components["schemas"]["StaffOut"] | null;
        };
        /**
         * ErrorOut
         * @description Every refusal: a message the frontend can show as it is.
         */
        ErrorOut: {
            /** Detail */
            detail: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HandBackIn */
        HandBackIn: {
            /** Reason */
            reason?: string | null;
        };
        /** HandBackOut */
        HandBackOut: {
            /** Reason */
            reason: string;
            /** By */
            by: string | null;
            /** Byname */
            byName: string | null;
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /** Health */
        Health: {
            /** Ok */
            ok: boolean;
            /**
             * Database
             * @enum {string}
             */
            database: "connected" | "unreachable";
        };
        /**
         * JobOut
         * @description Built with `JobOut.from_model(request, repeat_fault=...)`.
         */
        JobOut: {
            /** Id */
            id: string;
            /** Unitid */
            unitId: string;
            /** Tenantid */
            tenantId: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "maintenance" | "housekeeping";
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Assigneeid */
            assigneeId: string | null;
            /** Origin */
            origin: ("ops" | "tenant") | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Stagehistory */
            stageHistory: components["schemas"]["StageEntryOut"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Charge */
            charge: number | null;
            /** Completionnotes */
            completionNotes: string | null;
            schedule: components["schemas"]["ScheduleOut"] | null;
            /** Completionphotos */
            completionPhotos: components["schemas"]["PhotoOut"][];
            handBack: components["schemas"]["HandBackOut"] | null;
            unit: components["schemas"]["UnitOut"];
            property: components["schemas"]["PropertyOut"];
            tenant: components["schemas"]["TenantOut"] | null;
            assignee: components["schemas"]["StaffOut"] | null;
            repeatFault: components["schemas"]["RepeatFaultOut"] | null;
        };
        /**
         * ListingOut
         * @description `Listing` in types.ts.
         */
        ListingOut: {
            /** Slug */
            slug: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /** Purpose */
            purpose: string;
            /** Price */
            price: number;
            /** Currency */
            currency: string;
            /** Bedrooms */
            bedrooms: number;
            /** Bathrooms */
            bathrooms: number;
            /** Areasqft */
            areaSqft: number;
            location: components["schemas"]["LocationOut"];
            /** Images */
            images: string[];
            /** Description */
            description: string;
            /** Featured */
            featured: boolean;
        };
        /** LocationOut */
        LocationOut: {
            /** City */
            city: string;
            /** Area */
            area: string;
        };
        /** MonthTotal */
        MonthTotal: {
            /** Month */
            month: string;
            /** Total */
            total: number;
        };
        /**
         * NewRequestIn
         * @description `NewRequest` in operations.ts. `type`, `tenantId` and `charge` are not
         *     asked for: the category decides the trade, the unit decides the tenant, and
         *     the rate card decides the price.
         */
        NewRequestIn: {
            /** Unitid */
            unitId: string;
            /** Category */
            category: string;
            /**
             * Priority
             * @default normal
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /**
             * Summary
             * @default
             */
            summary: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Photos
             * @default []
             */
            photos: components["schemas"]["PhotoIn"][];
            /** Assigneeid */
            assigneeId?: string | null;
            /** Scheduleddate */
            scheduledDate?: string | null;
            /** Scheduledslot */
            scheduledSlot?: string | null;
            /**
             * Origin
             * @default ops
             * @enum {string}
             */
            origin: "ops" | "tenant";
        };
        /**
         * PhotoIn
         * @description `PhotoInput` in types.ts: anything without bytes is dropped.
         */
        PhotoIn: {
            /** Name */
            name?: string | null;
            /** Dataurl */
            dataUrl?: string | null;
        };
        /** PhotoOut */
        PhotoOut: {
            /** Name */
            name: string;
            /** Dataurl */
            dataUrl: string;
        };
        /** PriorityIn */
        PriorityIn: {
            /** Ids */
            ids: string[];
            /** Priority */
            priority: string;
        };
        /** PropertyOut */
        PropertyOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
        };
        /**
         * PropertyRollupOut
         * @description Cost and volume for one building, over the report period.
         */
        PropertyRollupOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Units */
            units: number;
            /** Requests */
            requests: number;
            /** Open */
            open: number;
            /** Unassigned */
            unassigned: number;
            /** Spend */
            spend: number;
            /** Spendperunit */
            spendPerUnit: number;
        };
        /** RateIn */
        RateIn: {
            /** Label */
            label?: string | null;
            /** Price */
            price?: number | string | null;
        };
        /**
         * RateOut
         * @description `HousekeepingRate`, plus when it left the card, if it has.
         */
        RateOut: {
            /** Servicetype */
            serviceType: string;
            /** Label */
            label: string;
            /** Price */
            price: number;
            /** Retiredat */
            retiredAt: string | null;
        };
        /**
         * RepeatFaultOut
         * @description A unit that keeps failing the same way: the repair-versus-replace
         *     signal. Derived when read, never stored.
         */
        RepeatFaultOut: {
            /** Category */
            category: string;
            /** Count */
            count: number;
            /** Spend */
            spend: number;
        };
        /** RequestIdsIn */
        RequestIdsIn: {
            /** Ids */
            ids: string[];
        };
        /**
         * RosterMemberOut
         * @description A staff member with their load, read off the requests they hold.
         */
        RosterMemberOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "maintenance" | "housekeeping";
            /** Photo */
            photo: string | null;
            /** Retiredat */
            retiredAt: string | null;
            /** Load */
            load: number;
            /** Capacity */
            capacity: number;
            /** Inprogress */
            inProgress: number;
            /** Closed */
            closed: number;
            /** Properties */
            properties: components["schemas"]["PropertyOut"][];
        };
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Slot */
            slot: string;
        };
        /**
         * ServiceRequestOut
         * @description `ServiceRequest` in types.ts. `stage` and `createdAt` are read from the
         *     history (see the model); `schedule` and `handBack` are rebuilt from their
         *     columns.
         */
        ServiceRequestOut: {
            /** Id */
            id: string;
            /** Unitid */
            unitId: string;
            /** Tenantid */
            tenantId: string | null;
            /**
             * Type
             * @enum {string}
             */
            type: "maintenance" | "housekeeping";
            /** Category */
            category: string;
            /**
             * Priority
             * @enum {string}
             */
            priority: "urgent" | "normal";
            /** Summary */
            summary: string;
            /** Description */
            description: string;
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Assigneeid */
            assigneeId: string | null;
            /** Origin */
            origin: ("ops" | "tenant") | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Stagehistory */
            stageHistory: components["schemas"]["StageEntryOut"][];
            /** Photos */
            photos: components["schemas"]["PhotoOut"][];
            /** Charge */
            charge: number | null;
            /** Completionnotes */
            completionNotes: string | null;
            schedule: components["schemas"]["ScheduleOut"] | null;
            /** Completionphotos */
            completionPhotos: components["schemas"]["PhotoOut"][];
            handBack: components["schemas"]["HandBackOut"] | null;
        };
        /** StaffIn */
        StaffIn: {
            /** Name */
            name?: string | null;
            /** Phone */
            phone?: string | null;
            /** Role */
            role?: string | null;
            /** Photo */
            photo?: string | null;
        };
        /** StaffOut */
        StaffOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /**
             * Role
             * @enum {string}
             */
            role: "maintenance" | "housekeeping";
            /** Photo */
            photo: string | null;
            /** Retiredat */
            retiredAt: string | null;
        };
        /** StageCount */
        StageCount: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /** Count */
            count: number;
        };
        /** StageEntryOut */
        StageEntryOut: {
            /**
             * Stage
             * @enum {string}
             */
            stage: "submitted" | "assigned" | "in-progress" | "done";
            /**
             * At
             * Format: date-time
             */
            at: string;
        };
        /**
         * TenantAccountOut
         * @description A tenant with the unit they occupy.
         */
        TenantAccountOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            unit: components["schemas"]["UnitOut"] | null;
            property: components["schemas"]["PropertyOut"] | null;
        };
        /** TenantOut */
        TenantOut: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
        };
        /** UnitOut */
        UnitOut: {
            /** Id */
            id: string;
            /** Propertyid */
            propertyId: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "occupied" | "under-maintenance" | "vacant";
            /** Tenantid */
            tenantId: string | null;
            /** Bedrooms */
            bedrooms: number;
            /** Bathrooms */
            bathrooms: number;
        };
        /**
         * UnitRecordOut
         * @description `UnitRecord`: a unit with what one trade's work there adds up to.
         */
        UnitRecordOut: {
            /** Id */
            id: string;
            /** Propertyid */
            propertyId: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "occupied" | "under-maintenance" | "vacant";
            /** Tenantid */
            tenantId: string | null;
            /** Bedrooms */
            bedrooms: number;
            /** Bathrooms */
            bathrooms: number;
            property: components["schemas"]["PropertyOut"];
            tenant: components["schemas"]["TenantOut"] | null;
            /** Requestcount */
            requestCount: number;
            /** Opencount */
            openCount: number;
            /** Lifetimespend */
            lifetimeSpend: number;
            /** Lastservicedat */
            lastServicedAt: string | null;
            repeatFault: components["schemas"]["RepeatFaultOut"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorklistCounts */
        WorklistCounts: {
            /** Left */
            left: number;
            /** Urgent */
            urgent: number;
            /** Closed */
            closed: number;
        };
        /**
         * WorklistOut
         * @description One technician's own work, split the way the screen draws it: the job
         *     to lead with, the rest queued behind it, and what's closed.
         */
        WorklistOut: {
            technician: components["schemas"]["StaffOut"];
            next: components["schemas"]["JobOut"] | null;
            /** Queued */
            queued: components["schemas"]["JobOut"][];
            /** Closed */
            closed: components["schemas"]["JobOut"][];
            counts: components["schemas"]["WorklistCounts"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    list_listings_listings_get: {
        parameters: {
            query?: {
                purpose?: string | null;
                type?: string | null;
                featured?: boolean | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_listing_listings__slug__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListingOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worklist_technicians__technician_id__worklist_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorklistOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_technicians__technician_id__jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_technicians__technician_id__jobs__job_id__start_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_job_technicians__technician_id__jobs__job_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompleteJobIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hand_back_job_technicians__technician_id__jobs__job_id__hand_back_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                technician_id: string;
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HandBackIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_requests_requests_get: {
        parameters: {
            query?: {
                stage?: ("submitted" | "assigned" | "in-progress" | "done") | null;
                type?: ("maintenance" | "housekeeping") | null;
                category?: string | null;
                priority?: ("urgent" | "normal") | null;
                tier?: ("emergency" | "standard") | null;
                propertyId?: string | null;
                unitId?: string | null;
                /** @description A staff id, or "unassigned". */
                assigneeId?: string | null;
                tenantId?: string | null;
                open?: boolean;
                search?: string | null;
                sort?: "age" | "newest";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedRequestOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_request_requests_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewRequestIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedRequestOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_request_requests__request_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrichedRequestOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assignment_candidates_requests__request_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                request_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidateOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_requests_requests_assign_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssignIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestOut"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_priority_requests_priority_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PriorityIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestOut"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_requests_requests_delete_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestIdsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ServiceRequestOut"][];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_units_units_get: {
        parameters: {
            query?: {
                propertyId?: string | null;
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRecordOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_unit_units__unit_id__get: {
        parameters: {
            query?: {
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path: {
                unit_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UnitRecordOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_properties_properties_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyOut"][];
                };
            };
        };
    };
    property_rollups_reports_properties_get: {
        parameters: {
            query?: {
                period?: ("month" | "quarter" | "year") | null;
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PropertyRollupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    category_rollups_reports_categories_get: {
        parameters: {
            query?: {
                period?: ("month" | "quarter" | "year") | null;
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CategoryRollupOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dashboard_reports_dashboard_get: {
        parameters: {
            query?: {
                period?: ("month" | "quarter" | "year") | null;
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    roster_staff_roster_get: {
        parameters: {
            query?: {
                type?: "maintenance" | "housekeeping";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RosterMemberOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staff_staff__staff_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_staff_staff__staff_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_staff_staff__staff_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_staff_staff_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rates_housekeeping_rates_get: {
        parameters: {
            query?: {
                includeRetired?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_rate_housekeeping_rates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retire_rate_housekeeping_rates__service_type__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                service_type: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateOut"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tenant_tenants__tenant_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                tenant_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TenantAccountOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
